name: rc-test
channels:
  - conda-forge
  - defaults
dependencies:
  - sqlalchemy==1.4.46
  - swifter==1.3.4
  - tqdm==4.65.0
  - regex=2022.7.9=py310h1a28f6b_0
  - requests=2.28.1=pyhd8ed1ab_1
  - requests-toolbelt=0.10.1=pyhd8ed1ab_0